package tmpl

import (
	"bytes"
	"encoding/json"
	"testing"
)

// helper: render and assert valid JSON output
func renderOK(t *testing.T, src string, vars map[string]string) ([]byte, map[string]string) {
	t.Helper()
	out, resolved, err := Render([]byte(src), vars)
	if err != nil {
		t.Fatalf("Render error: %v", err)
	}
	if !json.Valid(out) {
		t.Fatalf("output not valid JSON:\n%s", out)
	}
	return out, resolved
}

// --- legacy {{KEY}} syntax (no spaces) ---

func TestRender_LegacyPlaceholder(t *testing.T) {
	out, _ := renderOK(t, `{"server":"{{SERVER}}","port":{{PORT}}}`,
		map[string]string{"SERVER": "1.2.3.4", "PORT": "8388"})
	if !bytes.Contains(out, []byte("1.2.3.4")) {
		t.Errorf("SERVER not substituted: %s", out)
	}
}

// --- pongo2 / Jinja2 syntax ---

func TestRender_Pongo2Variable(t *testing.T) {
	out, _ := renderOK(t, `{"server":"{{ SERVER }}"}`,
		map[string]string{"SERVER": "10.0.0.1"})
	if !bytes.Contains(out, []byte("10.0.0.1")) {
		t.Errorf("pongo2 var not substituted: %s", out)
	}
}

func TestRender_Pongo2If(t *testing.T) {
	src := `{
		"tls_enabled": {% if TLS %}true{% else %}false{% endif %}
	}`
	out, _ := renderOK(t, src, map[string]string{"TLS": "1"})
	if !bytes.Contains(out, []byte("true")) {
		t.Errorf("if branch not taken: %s", out)
	}
}

func TestRender_Pongo2Filter_Default(t *testing.T) {
	// pongo2 filter syntax: {{ var|default:"value" }}
	out, _ := renderOK(t, `{"port":{{ PORT|default:"8388" }}}`,
		map[string]string{})
	if !bytes.Contains(out, []byte("8388")) {
		t.Errorf("default filter not applied: %s", out)
	}
}

// --- JSON5 features ---

func TestRender_LineCommentSlash(t *testing.T) {
	renderOK(t, `{
		"port": {{PORT}}, // listen port
		"method": "chacha20-ietf-poly1305"
	}`, map[string]string{"PORT": "8388"})
}

func TestRender_LineCommentHash(t *testing.T) {
	renderOK(t, `{
		"port": {{PORT}}, # listen port
		"method": "chacha20-ietf-poly1305"
	}`, map[string]string{"PORT": "8388"})
}

func TestRender_BlockComment(t *testing.T) {
	renderOK(t, `{
		/* server config */
		"port": {{PORT}}
	}`, map[string]string{"PORT": "8388"})
}

func TestRender_TrailingComma(t *testing.T) {
	renderOK(t, `{
		"a": 1,
		"b": 2,
	}`, map[string]string{})
}

func TestRender_CommentInsideString(t *testing.T) {
	out, _ := renderOK(t, `{"url":"https://example.com/path//foo"}`, map[string]string{})
	if !bytes.Contains(out, []byte("https://example.com/path//foo")) {
		t.Errorf("URL mangled: %s", out)
	}
}

// --- auto resolution ---

func TestRender_AutoPort(t *testing.T) {
	out, resolved, _ := Render([]byte(`{"port":{{PORT}}}`), map[string]string{"PORT": "{{AUTO_PORT}}"})
	if bytes.Contains(out, []byte("AUTO_PORT")) {
		t.Errorf("AUTO_PORT not resolved: %s", out)
	}
	if resolved["PORT"] == "{{AUTO_PORT}}" || resolved["PORT"] == "" {
		t.Errorf("PORT not resolved: %q", resolved["PORT"])
	}
}

func TestRender_AutoUUID(t *testing.T) {
	out, _, _ := Render([]byte(`{"uuid":"{{UUID}}"}`), map[string]string{"UUID": "{{AUTO_UUID}}"})
	if bytes.Contains(out, []byte("AUTO_UUID")) {
		t.Errorf("UUID not resolved: %s", out)
	}
}

func TestRender_AutoPassword(t *testing.T) {
	out, _, _ := Render([]byte(`{"pass":"{{PASSWORD}}"}`), map[string]string{"PASSWORD": "{{AUTO_PASSWORD}}"})
	if bytes.Contains(out, []byte("AUTO_PASSWORD")) {
		t.Errorf("PASSWORD not resolved: %s", out)
	}
}

func TestRender_AutoLiteralPreserved(t *testing.T) {
	// The word "auto" in a real config value must NOT be resolved.
	out, resolved, err := Render([]byte(`{"mode":"{{ MODE }}"}`), map[string]string{"MODE": "auto"})
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	if !bytes.Contains(out, []byte("auto")) {
		t.Errorf("literal 'auto' value was incorrectly resolved: %s", out)
	}
	if resolved["MODE"] != "auto" {
		t.Errorf("MODE should stay 'auto', got %q", resolved["MODE"])
	}
}

// --- combined: JSON5 + pongo2 + auto ---

func TestRender_Combined(t *testing.T) {
	src := `{
		// Shadowsocks config — generated by hiddify-health
		"method": "chacha20-ietf-poly1305", # required
		"password": "{{ PASSWORD }}",
		"listen_port": {{ PORT }},
		/* optional fields */
		"network": ["tcp","udp"],
	}`
	renderOK(t, src, map[string]string{"PORT": "{{AUTO_PORT}}", "PASSWORD": "{{AUTO_PASSWORD}}"})
}
